apiVersion: v1
kind: Service
metadata:
  name: testvm-http
  namespace: default
spec:
  ports:
  - port: 8080
    targetPort: 80
  selector:
    kubevirt.io/domain:  ubuntu-bionic
    kubevirt.io/size:    small
  type: LoadBalancer